### ISSUE TITLE
Install fails because a git submodule (tapcfg) is not available anymore

### ISSUE THREAD

**Issue by jeanthom** [timvideos/litex-buildenv#117]
Hi !

I came across this issue while trying to use litex-buildenv. I got asked for my GitHub credentials while running `scripts/download-env.sh` because the repository nizox/tapcfg isn't publicly available anymore on GitHub. This repository is a submodule of enjoy-digital's litedram.

This issue was fixed in LiteX yesterday (@enjoy-digital rehosted it on his GitHub account) :
https://github.com/enjoy-digital/litex/commit/a7378a721c039c89f6c339b9c0c50609f8769c0a

**Comment by mithro** [comment]
Queued the fix here -> https://github.com/timvideos/litex-buildenv/pull/118
