### ISSUE TITLE
Compilation issue with Conda's lm32 toolchain

### ISSUE THREAD

**Issue by jeanthom** [timvideos/litex-buildenv#120]
Hi !

I'm running into weird issue with the lm32 toolchain that litex-buildenv uses. The compiled firmware isn't working correctly, the firmware hangs just before or midway through printf calls ; however the BIOS works OK!

![capture d ecran 2018-12-29 a 11 31 09](https://user-images.githubusercontent.com/25333063/50537230-7c7de400-0b5d-11e9-8607-fdc57fd4c1a5.png)

@enjoy-digital sent me a toolchain ([http://www.das-labor.org/files/madex/lm32_linux_i386.tar.bz2](http://www.das-labor.org/files/madex/lm32_linux_i386.tar.bz2)) that works OK for me.

I am running litex-buildenv inside Xubuntu 18.04 virtualized using VirtualBox.

Attached to this issue are enjoy-digital/Chubby75 firmwares compiled with litex-buildenv and das-labor's toolchain :
[firmware-litex-buildenv.zip](https://github.com/timvideos/litex-buildenv/files/2716272/firmware-litex-buildenv.zip)
[firmware-das-labor.zip](https://github.com/timvideos/litex-buildenv/files/2716274/firmware-das-labor.zip)

**Comment by jeanthom** [comment]
I can't reproduce the issue nor explain why it works for me now... I'm closing this issue.

**Comment by mithro** [comment]
@jeanthom I'm very interested in getting Chubby75 support in litex-buildenv repository. Are you interested in adding it?

**Comment by jeanthom** [comment]
What should I do to provide Chubby75 support ? Adding platform & target scripts ?

**Comment by mithro** [comment]
@jeanthom Yeap!
