### ISSUE TITLE
HowTo LCA2018 FPGA needs "mor1kx" ?

### ISSUE THREAD

**Issue by CarlFK** [timvideos/litex-buildenv#155]
Should this be updated ?

`export CPU=or1k PLATFORM=arty TARGET=net`

`[WARNING] Deprecated, please update SoCCore's "cpu-type" to "mor1kx"`

**Comment by enjoy-digital** [comment]
Updating it would allow me to cleanup my code and remove this warning :)

**Comment by mithro** [comment]
If https://github.com/timvideos/litex-buildenv/pull/156 works, then we can update the documentation to use `CPU=mor1kx`.

**Comment by mithro** [comment]
The change so now that `CPU=mor1kx` should be used has been merged.
