### ISSUE TITLE
./scripts/download-env-root.sh doesn't exists

### ISSUE THREAD

**Issue by FrankBuss** [timvideos/litex-buildenv#194]
I was following the instructions at https://github.com/timvideos/litex-buildenv/blob/master/README.md but the file ./scripts/download-env-root.sh doesn't exists, only download-env.sh.

**Comment by mithro** [comment]
Looks like our documentation is out of date. The `download-env.sh` script has become https://github.com/timvideos/litex-buildenv/blob/master/scripts/debian-setup.sh

**Comment by FrankBuss** [comment]
This fails:
```
E: Failed to fetch http://ppa.launchpad.net/obsproject/obs-studio/ubuntu/dists/eoan/main/binary-i386/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/timvideos/fpga-support/ubuntu/dists/eoan/main/binary-amd64/Packages  404  Not Found
```

**Comment by mithro** [comment]
Seems we don't have eoan support. Try skipping this step?

**Comment by mithro** [comment]
This should now be fixed! Sorry about taking so long.
