### ISSUE TITLE
Add guides for NeTV2 and Pano Logic G2 to the Wiki

### ISSUE THREAD

**Issue by piotr-binkowski** [timvideos/litex-buildenv#255]
I don't see any way to create a PR for wiki changes so I decided to create a patch from my changes that can be reviewed and then merged
[0001-add-howtos-for-pano-logic-g2-and-netv2.patch.txt](https://github.com/timvideos/litex-buildenv/files/3916410/0001-add-howtos-for-pano-logic-g2-and-netv2.patch.txt)

**Comment by mithro** [comment]
You should just be able to edit the wiki directly?

**Comment by piotr-binkowski** [comment]
I just wasn't sure if I should edit it directly, I added those HowTos to the wiki
* https://github.com/timvideos/litex-buildenv/wiki/HowTo-Linux-on-Pano-Logic-G2
* https://github.com/timvideos/litex-buildenv/wiki/HowTo-HDMI2PCIe-on-NeTV2
and linked to them in [HowTos page](https://github.com/timvideos/litex-buildenv/wiki/HowTos)
