### ISSUE TITLE
Wiki formatting seems broken?

### ISSUE THREAD

**Issue by bunnie** [timvideos/litex-buildenv#32]
I'm trying to write up docs on how to use litex, but I can't seem to get code sections to show up correctly in the wiki formatting. Please have a look at 

https://github.com/timvideos/litex-buildenv/wiki/LiteX-for-Hardware-Engineers#Litescope_Sampler

for an example of the problem. The code looks fine when I edit it in a source editor, but when it gets pulled into github it's all kind of messed up. 

Any ideas on how to fix this would be great, but for now, I'm just going to write docs so they look good in a text editor but it'll be basically unusable by web browsing.

**Comment by mithro** [comment]
https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting

**Comment by mithro** [comment]
https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by bunnie** [comment]
Actually, this is using the "mediawiki" format for these docs -- so there's supposed to be <nowiki> tags. I'm not using Markdown, so the cheatsheets you linked me to don't help.

If you look at the docs, I manage to get github to respect <nowiki> tags for maybe the first dozen code blocks, but as we start to go down the page it gets confused and stops rendering <nowiki> tags. 

I'm using the "mediawiki" format because it supports ToC generation. Github Markdown doesn't support ToC, and the doc is large enough that it needs  ToC of its own, otherwise it's unnavigable. 

So I guess maybe the questions are:

1) do you know how to generate a ToC using the Markdown syntax?
2) any ideas on how to tame github's <nowiki> tags?

**Comment by bunnie** [comment]
Alright, I found a somewhat palatable workaround. 

When using <nowiki> tags, use it as a 

<pre><nowiki> combo, and include one line of dummy text. The dummy text is always deleted by github during rendering. So to include code, do this:

<pre><nowiki>
dummy text

Code here
</nowiki></pre>

that seems to work, at least for now...

**Comment by bunnie** [comment]
Ugh, well, of course tags don't render in comments. it's

`
<pre><nowiki>
dummy text

code here
</nowiki></pre>
`
as a work-around for mediawiki bugs.

**Comment by bunnie** [comment]
Fuck. still doesn't render. The point is, use a tag of "pre" and "nowiki" in series, and a closing tag set of "nowiki" and "pre" in the end. Along with one line of dummy text.

**Comment by mithro** [comment]
Mediawiki format isn't going to get you TOC according to this -> https://help.github.com/articles/supported-mediawiki-formats/

> ## Unsupported MediaWiki syntaxes
> * Transclusion
> * Definition lists
> * Indentation
> * Table of contents

**Comment by mithro** [comment]
Yet it seems to work....

**Comment by mithro** [comment]
I have never used anything apart from Markdown in a GitHub wiki before. Apparently ASCIIDoc also has TOC support using;
```adoc
:toc: macro
:toc-title:
:toclevels: 99

# Table of Contents
toc::[]
```

**Comment by mithro** [comment]
There is lots of complaining about this here -> https://github.com/isaacs/github/issues/215

**Comment by mithro** [comment]
BTW - I would definitely recommend splitting this page into multiple files...
