### ISSUE TITLE
Need significantly clearer instructions for UART on TinyFPGA BX

### ISSUE THREAD

**Issue by mithro** [timvideos/litex-buildenv#97]
There need to be a lot clearer instructions for the TinyFPGA BX UART attachment. Should include clear *pictures* of the set up and which pins are connected.

Which way around is TX? Which way around is RX? How would you connected it to a Pmod USB UART?

**Comment by cr1901** [comment]
Just updated the [wiki page](https://github.com/timvideos/litex-buildenv/wiki/HowTo-FuPy-on-iCE40-Boards). If it's to your satisfaction, I think this can be closed.

**Comment by mithro** [comment]
That is super nice looking! Great work.
